### ISSUE TITLE
Get all the notifications in the background

### ISSUE THREAD

**Issue by adgad** [Financial-Times/next-myft-email-generator#1]
Rather than making a request to get notifications for every user, should be able to scan/query the dynamodb table directly inside the job in the background (or polling).

**Comment by commuterjoy** [comment]
Or maintain a list of user ids who have received a notification in the last n hours (in a redis set?).

**Comment by commuterjoy** [comment]
Or a queue for that matter. Sqs!

**Comment by wheresrhys** [comment]
this is relatively redundant now
